version: '3'

services:
  producer:
    image: producer
    depends_on: ['consumer']
    environment:
      - CONSUMER_SERVICE=consumer:12345

  consumer:
    image: consumer
    depends_on: ['redis']
    environment:
      - LISTEN_ADDR=0.0.0.0:12345
      - REDIS=redis:6379

  redis:
    image: redis:alpine
